version: "3"
services:
  php:
    build: php
    ports: 
      - 15000:80
    volumes:
      - ./src/:/var/www/html/
    links:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: qKv7rAzF
      MYSQL_USER: dev
      MYSQL_PASSWORD: 97yc2Gse
      MYSQL_DATABASE: app
    ports:
      - 3306:3306
    volumes:
      - ./db/:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci