FROM php:7.0-apache
RUN apt-get update && apt-get install -y less
RUN docker-php-ext-install mysqli

ENV MYSQL_ROOT_PASSWORD=qKv7rAzF
ENV MYSQL_USER=dev
ENV MYSQL_PASSWORD=97yc2Gse
ENV MYSQL_DATABASE=app